Working branch
vladimir-bogdanovic/dinner-menu pull request #1
Opened 2023-08-02 18:38 UTC by vladimir-bogdanovic

2023-08-02 18:54 UTC, radisa-bogdanovic requested changes
Ovo je za sada

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/add-new-meal/add-new-meal.component.css
> +  color: rgb(84, 83, 83);
use #hex instead of rgb

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/add-new-meal/add-new-meal.component.css
> +  background-color: red;
disabled button je uvek sive boje ili neke tamnije a ne crvene

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/add-new-meal/add-new-meal.component.css
> +  border: 1px solid red;
touched ne mora da znaci da je error. Handluj ovo sa reaktivnim formama i dodaj klasu ako je error na inputu

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/add-new-meal/add-new-meal.component.html
> +    <div class="label-and-input-div">
name of clas : 'add-meal__linput-container'

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/add-new-meal/add-new-meal.component.html
> +      <input type="text" formControlName="strIngredient2" />
ovde ces da stavis jedan input i pored njega action button sa contentom '+' na koji user kada klikne pojavi se novi input i samim tim dinamicno dodajes ili oduzimas inpute

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/add-new-meal/add-new-meal.component.html
> +        (must <b></b>e in first ingredient input)</span
b tag?

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/add-new-meal/add-new-meal.component.html
> +      <button class="button" type="submit" [disabled]="!addNewMealForm.valid">
deskriptivniji budi sa nazivom klase. Ne samo button.

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/add-new-meal/add-new-meal.component.html
> +        <span *ngIf="!addNewMealForm.valid">Enter mandatory data!</span>
else ne 2 if

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/add-new-meal/add-new-meal.component.ts
> +    console.log(this.addNewMealForm);
remove cl

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/add-new-meal/add-new-meal.component.ts
> +      strIngredient4: new FormControl(),
i na primer kada user doda neki input dodavaces i novu formControlu dinamicki. tj ako ukloni uklanjaces

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/app-routing.module.ts
>    },
fali ti path zza error, tj ako nalupa neku adresu

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/menu-page/category-meals/category-meals.component.ts
ukloni prazna polja

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/menu-page/category-meals/category-meals.component.ts
> +  addedItemInfo!: any;
zasto je any, ukloni any

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/menu-page/category-meals/category-meals.component.ts
>    // params
remove comented code

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/menu-page/category-meals/category-meals.component.ts
> +    // geting added item from local storage
Ukloni komentare

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/menu-page/category-meals/category-meals.component.ts
> +    if (id === undefined) {
if (id)  undefined je isto sto i false u js tako da moze i ovako da se pise

2023-08-02 18:54 UTC, radisa-bogdanovic commented on restaurant/src/app/menu-page/category-meals/category-meals.component.ts
> +    this.router.navigate(['menu/' + this.param + '/' + 'new-meal']);
+ '/new-meal' umesto da dodajes jos jedan +

2023-08-04 19:57 UTC, vladimir-bogdanovic commented
tomorrow we continue...

2023-08-04 19:58 UTC, merged